on:
  push:
    branches:
      - main




jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@v3
      - name: "Accessing Docker"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
      - name: "PRINTING A WELCOME"
        run: echo "WELCOME zezo"
