on:
  push:
    branches:
      - main




jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@v3
      
      - name: "login Docker"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      - name: "bilding docker imge"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/newOne .

       - name: "push to docker hup"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/newOne 

      - name: "PRINTING A WELCOME"
        run: echo "WELCOME zezo"
